WebApp/Controllers/BookingServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using WebApp.Commands;
using WebApp.Mappers;
using WebApp.RESTClients;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class BookingServiceController : Controller
    {
        private readonly IBookingServiceAPI _bookingServiceAPI;
        private readonly ILogger _logger;
        private ResiliencyHelper _resiliencyHelper;

        public BookingServiceController(IBookingServiceAPI bookingServiceAPI,
            ILogger<BookingServiceController> logger)
        {
            _bookingServiceAPI = bookingServiceAPI;
            _logger = logger;
            _resiliencyHelper = new ResiliencyHelper(_logger);
        }

        [HttpGet]
        public async Task<IActionResult> BookAFlight(string id)
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                var model = new FlightBookingViewModel
                {
                    Flight = await _bookingServiceAPI.GetFlightByCode(id),
                    Customers = await GetAvailableCustomerList(),
                    Numbers = GetRange()
                };
                return View(model);
            }, View("Offline", new FlightBookingOfflineViewModel()));
        }

        [HttpPost]
        public async Task<IActionResult> BookAFlight([FromForm] FlightBookingViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Flight =await _bookingServiceAPI.GetFlightById(model.FlightId);
                model.Customer = await _bookingServiceAPI.GetCustomerById(model.SelectedCustomerId);

                return await _resiliencyHelper.ExecuteResilient(async () =>
                {
                    BookedFlight cmd = model.MapToBookedFlight();
                    await _bookingServiceAPI.BookAFlight(cmd);
                   return RedirectToAction("Index", "FlightService");
                }, View("Offline", new FlightBookingOfflineViewModel()));
            }
            else
            {
                return View("BookAFlight", model);
            }
        }

        private async Task<IEnumerable<SelectListItem>> GetAvailableCustomerList()
        {
            var customers = await _bookingServiceAPI.GetCustomers();
            return customers.Select(c =>
                new SelectListItem
                {
                    Value = c.CustomerId.ToString(),
                    Text = $"{c.Name}"
                });
        }

        private IEnumerable<SelectListItem> GetRange()
        {
            return Enumerable.Range(1, 5)
                .Select(n => new SelectListItem
                {
                    Value = n.ToString(),
                    Text = n.ToString()
                });
        }
    }
}

WebApp/Controllers/FlightServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApp.Commands;
using WebApp.Mappers;
using WebApp.Models;
using WebApp.RESTClients;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class FlightServiceController : Controller
    {
        private readonly IFlightServiceAPI _flightServiceAPI;
        private readonly ILogger _logger;
        private ResiliencyHelper _resiliencyHelper;

        public FlightServiceController(IFlightServiceAPI flightServiceAPI,
            ILogger<FlightServiceController> logger)
        {
            _flightServiceAPI = flightServiceAPI;
            _logger = logger;
            _resiliencyHelper = new ResiliencyHelper(_logger);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                var model = new FlightViewModel
                {
                    Flights = await _flightServiceAPI.GetFlights()
                };
                return View(model);
            }, View("Offline", new FlightOfflineViewModel()));
        }

        [HttpPost]
        public async Task<IActionResult> SearchFlight(FlightFilterViewModel filterModel)
        {
            return await _resiliencyHelper.ExecuteResilient(async () =>
            {
                var model = new FlightViewModel
                {
                    Flights = await _flightServiceAPI.SearchFlight(filterModel.From,filterModel.To,filterModel.Date)
                };
                return View(nameof(Index), model);
            }, View("Offline", new FlightOfflineViewModel()));
        }

        [HttpGet]
        public IActionResult New()
        {
            var model = new FlightNewViewModel
            {
                Flight = new Flight()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromForm] FlightNewViewModel inputModel)
        {
            if (ModelState.IsValid)
            {
                return await _resiliencyHelper.ExecuteResilient(async () =>
                {
                    RegisterFlight cmd = inputModel.MapToRegisterFlight();
                    await _flightServiceAPI.RegisterFlight(cmd);
                    return RedirectToAction("Index");
                }, View("Offline", new FlightOfflineViewModel()));
            }
            else
            {
                return View("New", inputModel);
            }
        }
    }
}

WebApp/Views/FlightService/Index.cshtml
@model WebApp.ViewModels.FlightViewModel
@{
	ViewData["Title"] = "Flight Overview";
}

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<br />

<form method="post">
	<div class="col-md-12 search-flight row">
		<div class="col-md-3">
			<input class="form-control" type="text" name="From" style="float:right;" placeholder="From" />
		</div>
		<div class="col-md-3">
			<input class="form-control" type="text" name="To" style="float:right;" placeholder="To" />
		</div>
		<div class="col-md-3">
			<input class="form-control" type="date" name="Date" asp-for="@DateTime.UtcNow" style="float:right;" placeholder="Date" />
		</div>
		<div class="col-md-3">
			<button style="float:right;" type="submit" class="btn btn-block btn-primary" asp-action="SearchFlight" asp-controller="FlightService">Search</button>
		</div>
	</div>
</form>

<br />
<br />
<br />
<table class="table">
	<thead>
		<tr>
			<th>From</th>
			<th>To</th>
			<th>Airline</th>
			<th>Duration</th>
			<th>Empty seets</th>
			<th>Price</th>
			<th>Date</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var flight in Model.Flights)
		{
			<tr>
				<td>@flight.From</td>
				<td>@flight.To</td>
				<td>@flight.AirlineName</td>
				<td>@flight.Duration</td>
				<td>@flight.EmptySeets</td>
				<td>@flight.Price ‎€</td>
				<td>@flight.FlightTime.ToString("dd/MM/yyyy")</td>
				<td>
					<span><a id="@flight.FlightCode" asp-route-id="@flight.FlightCode" asp-action="BookAFlight" asp-controller="BookingService" class="btn btn-default">Book a flight</a></span>
				</td>
			</tr>
		}
	</tbody>
</table>
<a id="RegisterFlightButton" asp-action="New" asp-controller="FlightService" class="btn btn-default">Add new flight</a>

WebApp/Views/FlightService/New.cshtml
@model WebApp.ViewModels.FlightNewViewModel
@{
	ViewData["Title"] = "Add Flight";
}


<h3 id="PageTitle">Register customer</h3>

<form asp-controller="FlightService" asp-action="Register" method="post">
	<div class="form-group">
		<label asp-for="Flight.FlightCode"></label>
		<input asp-for="Flight.FlightCode" type="text" class="form-control" />
		<span asp-validation-for="Flight.FlightCode" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Flight.From"></label>
		<input asp-for="Flight.From" type="text" class="form-control" />
		<span asp-validation-for="Flight.From" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Flight.To"></label>
		<input asp-for="Flight.To" type="text" class="form-control" />
		<span asp-validation-for="Flight.To" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Flight.AirlineName"></label>
		<input asp-for="Flight.AirlineName" type="text" class="form-control" />
		<span asp-validation-for="Flight.AirlineName" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Flight.Duration"></label>
		<input asp-for="Flight.Duration" type="text" class="form-control" />
		<span asp-validation-for="Flight.Duration" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Flight.Price"></label>
		<input asp-for="Flight.Price" type="text" class="form-control" />
		<span asp-validation-for="Flight.Price" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Flight.EmptySeets"></label>
		<input asp-for="Flight.EmptySeets" type="text" class="form-control" />
		<span asp-validation-for="Flight.EmptySeets" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Flight.FlightTime"></label>
		<input asp-for="Flight.FlightTime" type="date" class="form-control" />
		<span asp-validation-for="Flight.FlightTime" class="text-danger"></span>
	</div>
	<span><button id="SubmitButton" type="submit" class="btn btn-default">Register</button></span>
	<span><a id="CancelButton" asp-action="Index" asp-controller="FlightService" class="btn btn-default">Cancel</a></span>
</form>

WebApp/Views/FlightService/Offline.cshtml
@model WebApp.ViewModels.FlightOfflineViewModel
@{
    ViewData["Title"] = "Offline";
}
<h3 id="PageTitle">Flight Management - offline</h3>
<p>Unfortunately the flight management module is offline at the moment. Try again soon.</p>